-- Drop the table if it exists to start fresh with the new schema.
DROP TABLE IF EXISTS public.workflows;

-- Table to store analyzed workflows with an auto-incrementing numeric ID.
CREATE TABLE public.workflows (
    -- Auto-incrementing numeric primary key (1, 2, 3, ...).
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Stable unique identifier used by the application for upserts.
    workflow_uuid TEXT UNIQUE NOT NULL,

    "fileName" TEXT,
    "flowName" TEXT,
    "mainArea" TEXT,
    "secondaryAreas" JSONB,
    "mainFunction" TEXT,
    "automationDestinations" JSONB,
    "dataOrigins" JSONB,
    "keyNodes" JSONB,
    complexity TEXT,
    "shortDescription" TEXT,
    "useCaseExamples" JSONB,
    similarities JSONB,

    -- Timestamp for when the record was created.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) for the table. It's a good security practice in Supabase.
ALTER TABLE public.workflows ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Allow public read access (anon) to all records.
-- This allows anyone with the anonymous key to read the data.
CREATE POLICY "Enable read access for all users"
ON public.workflows
FOR SELECT
USING (true);

-- RLS Policy: Allow anonymous users (with the anon key) to insert and update records.
-- This is necessary for the `upsert` function from the application to work.
CREATE POLICY "Enable insert and update for anonymous users"
ON public.workflows
FOR ALL
USING (true)
WITH CHECK (true);
